# .travis.yml
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  yarn: true

script:
- cd website && yarn install && yarn build

jobs:
  include:
  - stage: Deploy
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: GH_TOKEN
      keep-history: true
      local-dir: website/build
      on:
        branch: master
