# .travis.yml
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  yarn: true

script:
- cd website && yarn install yarn build

jobs:
  include:
  - stage: Deploy
    if: (NOT type IN (pull_request)) AND ((branch = develop) OR (branch = master))
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: GH_TOKEN
      keep-history: true
      local-dir: build
      on:
        branch: master
